location = /altcha-challenge {
    access_by_lua_block { return }
    default_type application/json;
    add_header 'Access-Control-Allow-Origin' '*' always;
    content_by_lua_block {
        local altcha = require("plugins.crowdsec.altcha")
        local cs_config = require("plugins.crowdsec.config")
        local conf, err = cs_config.loadConfig("/etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf", true)
	local secret = conf.SECRET_KEY 
        local challenge = altcha.create_challenge(secret, 50000)
        ngx.say(require("cjson").encode(challenge))
    }
}

location = /altcha.js {
    access_by_lua_block { return }
    
    alias /var/lib/crowdsec/lua/templates/altcha.min.js;
    default_type application/javascript;
    
    # Mettre en cache dans le navigateur pour de meilleures performances
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header Access-Control-Allow-Origin "*";

}
